language: python
sudo: false
python:
 - "2.7"
 - "3.3"
 - "3.4"
 - "pypy"

install:
 - "pip install -r requirements.txt"
 - "pip install pytest coverage pytest-cov"
 - "pip install ."

script:
  - "py.test --cov upass --cov-report term-missing tests/"

notifications:
  email:
    on_success: always # use "change" to get less emails
    on_failure: always
